# -*- coding: utf-8 -*-
"""Web_trial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13uKuDoZ5aAvLccOeRbly2Vk3Qru3Tp-H
"""

!pip install streamlit pandas openpyxl yagmail stripe
!npm install -g localtunnel

import streamlit as st

st.write('Hello, *World!* :sunglasses:')